---

language: ruby

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

before_install:
  - gem update --system

script:
  - bundle exec rake

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head
